import React from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function Landing() {
  const { user } = useAuth();
  const navigate = useNavigate();

  const handleAction = (path) => {
    navigate(path);
  };

  const popularTopics = [
    { subject: "Data Structures", topic: "Stacks & Queues", icon: "📦" },
    { subject: "Operating Systems", topic: "Process Scheduling", icon: "💻" },
    { subject: "Computer Networks", topic: "TCP/IP & OSI Model", icon: "🌐" },
    { subject: "DBMS", topic: "SQL & Normalization", icon: "🗄️" },
    { subject: "Java", topic: "OOP & Collections", icon: "☕" },
    { subject: "Mathematics", topic: "Probability & Calculus", icon: "📐" },
  ];

  const features = [
    {
      title: "AI Quiz Generation",
      description: "Generate complete, syllabus-accurate quizzes with single correct answers and detailed explanations in seconds.",
      icon: "✨",
      gradient: "from-pink-500/20 to-purple-500/20",
      border: "border-pink-500/30",
    },
    {
      title: "Solo Practice",
      description: "Practice at your own pace with customizable timers, instant score evaluation, and in-depth question breakdowns.",
      icon: "🎯",
      gradient: "from-purple-500/20 to-indigo-500/20",
      border: "border-purple-500/30",
    },
    {
      title: "Live Multiplayer Arena",
      description: "Host live game rooms, share 6-character room codes, and compete with friends in real-time with synchronized timers.",
      icon: "⚡",
      gradient: "from-indigo-500/20 to-blue-500/20",
      border: "border-indigo-500/30",
    },
    {
      title: "Smart Explanations",
      description: "Learn from every question with AI-crafted educational explanations clarifying why an answer is right or wrong.",
      icon: "💡",
      gradient: "from-amber-500/20 to-pink-500/20",
      border: "border-amber-500/30",
    },
    {
      title: "Performance Tracking",
      description: "Track your accuracy, identify weak subjects, and let AI automatically generate quizzes focused on your weak areas.",
      icon: "📈",
      gradient: "from-emerald-500/20 to-teal-500/20",
      border: "border-emerald-500/30",
    },
    {
      title: "Global Leaderboards",
      description: "Climb the ranks on global leaderboards and see how your speed and accuracy compare against other learners.",
      icon: "🏆",
      gradient: "from-yellow-500/20 to-amber-500/20",
      border: "border-yellow-500/30",
    },
  ];

  const steps = [
    { step: "01", title: "Choose Preferences", desc: "Select subject, difficulty, language, and timer rules.", icon: "⚙️" },
    { step: "02", title: "Generate with AI", desc: "AI builds balanced questions, plausible distractors & explanations.", icon: "🤖" },
    { step: "03", title: "Play Solo or Live", desc: "Review the quiz, start solo practice or invite friends to a live room.", icon: "🎮" },
    { step: "04", title: "Learn & Improve", desc: "Review answers, inspect weak areas, and generate target practice quizzes.", icon: "🚀" },
  ];

  return (
    <div className="min-h-screen bg-[#080014] text-white selection:bg-pink-500 selection:text-white relative overflow-hidden">
      {/* Background ambient lighting */}
      <div className="fixed top-[-100px] left-1/2 -translate-x-1/2 w-[700px] h-[500px] bg-gradient-to-b from-purple-600/20 via-pink-600/15 to-transparent blur-[140px] pointer-events-none" />
      <div className="fixed bottom-0 right-0 w-[500px] h-[400px] bg-indigo-600/10 blur-[130px] pointer-events-none" />

      {/* Hero Section */}
      <section className="relative z-10 pt-16 sm:pt-24 pb-20 px-4 sm:px-6 max-w-6xl mx-auto text-center">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-purple-500/30 bg-purple-500/10 backdrop-blur-md mb-8 animate-fade">
          <span className="text-xs font-bold text-pink-400 uppercase tracking-widest">
            ✦ AI-Powered Multiplayer Quiz Platform
          </span>
        </div>

        <h1 className="text-4xl sm:text-6xl md:text-7xl font-extrabold tracking-tight leading-[1.1] mb-6">
          Your Quiz.
          <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-pink-400 via-purple-400 to-indigo-400">
            Generated by AI.
          </span>
        </h1>

        <p className="text-base sm:text-xl text-gray-300 max-w-2xl mx-auto mb-10 leading-relaxed font-normal">
          Choose a topic, set your difficulty, and let AI build the quiz.
          Practice solo, challenge friends in live multiplayer rooms, and master your weak areas.
        </p>

        {/* Hero CTA Buttons */}
        <div className="flex flex-wrap items-center justify-center gap-4 mb-16">
          <button
            onClick={() => handleAction(user ? "/create-quiz" : "/login")}
            className="px-7 py-4 rounded-2xl font-bold text-base text-white bg-gradient-to-r from-pink-500 via-purple-500 to-indigo-600 hover:from-pink-400 hover:to-indigo-500 shadow-xl shadow-purple-900/30 hover:scale-[1.03] active:scale-95 transition-all duration-200"
          >
            ✨ Create AI Quiz
          </button>

          <button
            onClick={() => handleAction(user ? "/practice" : "/login")}
            className="px-7 py-4 rounded-2xl font-bold text-base text-white bg-white/5 border border-white/15 hover:bg-white/10 hover:border-pink-500/40 hover:scale-[1.03] active:scale-95 transition-all duration-200 backdrop-blur-md"
          >
            🎯 Practice Solo
          </button>

          <button
            onClick={() => handleAction(user ? "/create-room" : "/login")}
            className="px-7 py-4 rounded-2xl font-bold text-base text-white bg-white/5 border border-white/15 hover:bg-white/10 hover:border-purple-500/40 hover:scale-[1.03] active:scale-95 transition-all duration-200 backdrop-blur-md"
          >
            ⚡ Play Multiplayer
          </button>
        </div>

        {/* Quick Topic Chips */}
        <div className="max-w-4xl mx-auto pt-6 border-t border-white/10">
          <p className="text-xs uppercase tracking-wider text-gray-400 mb-4 font-semibold">
            Popular Subjects Ready For AI Generation
          </p>
          <div className="flex flex-wrap justify-center gap-2.5">
            {popularTopics.map((pt) => (
              <button
                key={pt.subject}
                onClick={() =>
                  navigate(user ? "/create-quiz" : "/login", {
                    state: { subject: pt.subject, topic: pt.topic },
                  })
                }
                className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-white/5 border border-white/10 text-xs sm:text-sm text-gray-300 hover:border-pink-500/40 hover:text-white hover:bg-white/10 transition"
              >
                <span>{pt.icon}</span>
                <span className="font-medium">{pt.subject}</span>
                <span className="text-gray-500 text-xs">({pt.topic})</span>
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* 4-Step Workflow Section */}
      <section className="relative z-10 py-16 px-4 sm:px-6 max-w-6xl mx-auto border-t border-white/10">
        <div className="text-center mb-14">
          <p className="text-xs font-bold text-pink-400 uppercase tracking-widest mb-2">
            How It Works
          </p>
          <h2 className="text-2xl sm:text-4xl font-extrabold text-white">
            Choose → Generate → Play → Improve
          </h2>
          <p className="text-gray-400 text-sm sm:text-base mt-2">
            From topic prompt to live leaderboard in less than 30 seconds.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {steps.map((st) => (
            <div
              key={st.step}
              className="relative p-6 rounded-3xl bg-white/[0.04] border border-white/10 backdrop-blur-xl hover:border-pink-500/30 transition group"
            >
              <div className="flex items-center justify-between mb-4">
                <span className="text-xs font-extrabold px-2.5 py-1 rounded-lg bg-pink-500/10 text-pink-400 border border-pink-500/20">
                  {st.step}
                </span>
                <span className="text-3xl group-hover:scale-110 transition">{st.icon}</span>
              </div>
              <h3 className="text-lg font-bold text-white mb-2">{st.title}</h3>
              <p className="text-sm text-gray-400 leading-relaxed">{st.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Feature Cards Grid */}
      <section className="relative z-10 py-16 px-4 sm:px-6 max-w-6xl mx-auto border-t border-white/10">
        <div className="text-center mb-14">
          <p className="text-xs font-bold text-purple-400 uppercase tracking-widest mb-2">
            Features Built For Learners & Hosts
          </p>
          <h2 className="text-2xl sm:text-4xl font-extrabold text-white">
            Everything You Need For Quiz Mastery
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feat) => (
            <div
              key={feat.title}
              className={`p-7 rounded-3xl bg-gradient-to-br ${feat.gradient} border ${feat.border} backdrop-blur-xl shadow-xl transition-all duration-300 hover:scale-[1.02]`}
            >
              <div className="text-4xl mb-4">{feat.icon}</div>
              <h3 className="text-xl font-bold text-white mb-2">{feat.title}</h3>
              <p className="text-sm text-gray-300 leading-relaxed">{feat.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Bottom CTA Banner */}
      <section className="relative z-10 py-20 px-4 sm:px-6 max-w-4xl mx-auto text-center">
        <div className="p-8 sm:p-12 rounded-3xl bg-gradient-to-r from-pink-600/20 via-purple-600/20 to-indigo-600/20 border border-purple-500/30 backdrop-blur-2xl shadow-2xl">
          <h2 className="text-2xl sm:text-4xl font-extrabold text-white mb-4">
            Ready to test your knowledge with AI?
          </h2>
          <p className="text-gray-300 text-sm sm:text-base max-w-xl mx-auto mb-8">
            Create your custom quiz in seconds or join a live room with friends.
          </p>
          <button
            onClick={() => handleAction(user ? "/create-quiz" : "/register")}
            className="px-8 py-4 rounded-2xl font-bold text-base text-white bg-gradient-to-r from-pink-500 to-purple-600 hover:from-pink-400 hover:to-purple-500 shadow-xl shadow-pink-500/25 hover:scale-105 transition"
          >
            {user ? "🚀 Create Your First AI Quiz" : "✨ Create Free Account"}
          </button>
        </div>
      </section>
    </div>
  );
}
